Repository SiSt-ProjectTeam/CultureCenter, pull requests merged in 2023-12, with the labels that each got.

#47 장바구니 tiles처리완료, tiles.xml 순서바꿔줌
  CultureCenter/src/main/java/com/culture/demo/controller/MyPageCartController.java
  CultureCenter/src/main/webapp/WEB-INF/tiles/tiles.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/cart/list.jsp
Labels: 🐞 Bug

#68 수강내역 - 수강 내역 조회
  .gitignore
  CultureCenter/bin/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
  CultureCenter/pom.xml
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctPersonalDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AtlctMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/SampleMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctService.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/AtlctMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypage_atlct.js
  CultureCenter/target/classes/com/culture/demo/AtlctMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.xml
Labels: 🔨 Maintenance, ✨ Feature

#74 수강내역 - 세부 기능 추가 및 오류 수정 (페이징처리)
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
Labels: 🔨 Maintenance, ✨ Feature

#75 수강내역 / 장바구니 기능 추가
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/참고문서--이슈-생성-템플릿.md
  CultureCenter/src/main/java/com/culture/demo/controller/MyPageCartController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/CartDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MyPageCartMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/CartService.java
  CultureCenter/src/main/java/com/culture/demo/service/CartServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MyPageCartMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/cart/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/community/reviewController.js
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypage_cart.js
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MyPageCartMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
  README.md
Labels: 🔨 Maintenance, ✨ Feature

#76 수강내역 - 내역 상세 보기 페이지 이동 (+데이터 출력)
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmUpdateDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AtlctMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctService.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/view.jsp
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/target/classes/log4j.xml
Labels: 🔨 Maintenance, ✨ Feature

#77 마이페이지 팝업 + 정보조회
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmUpdateDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctService.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/SampleService.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/inc/header.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/view.jsp
  CultureCenter/src/main/webapp/resources/common/common.js
  CultureCenter/src/main/webapp/resources/common/js/common.js
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
Labels: ✨ Feature

#79 강좌 목록 출력하기
  CultureCenter/src/main/java/AppSearchService/LecSearchService.java
  CultureCenter/src/main/java/AppSearchService/LecSearchServiceImpl.java
  CultureCenter/src/main/java/AppSearchService/SampleService.java
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/controller/InformationGuideController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/tiles/tiles.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/guide/online/list.jsp
  CultureCenter/src/main/webapp/resources/common/images/icon-two-depth-select-check-black.svg
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
Labels: ⚙ Setting, ✨ Feature

#80 장바구니추가 & fnc.paraAjax수
  CultureCenter/src/main/java/com/culture/demo/controller/MemberController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MyPageCartController.java
  CultureCenter/src/main/java/com/culture/demo/domain/CartDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MyPageCartMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/CartService.java
  CultureCenter/src/main/java/com/culture/demo/service/CartServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MyPageCartMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/cart/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypage_cart.js
  CultureCenter/target/classes/com/culture/demo/mapper/MyPageCartMapper.xml
  CultureCenter/target/classes/log4j.xml
Labels: 🔨 Maintenance, ✨ Feature

#81 장바구니 추가 및 강좌 목록 출력 기능 추가
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/controller/HomeController.java
  CultureCenter/src/main/java/com/culture/demo/controller/InformationGuideController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MemberController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MyPageCartController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageAtlctController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/CartDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmUpdateDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/SearchBranchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AtlctMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/LecSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MyPageCartMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctService.java
  CultureCenter/src/main/java/com/culture/demo/service/AtlctServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/CartService.java
  CultureCenter/src/main/java/com/culture/demo/service/CartServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/SampleService.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MyPageCartMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/tiles/tiles.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/inc/header.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/guide/online/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/view.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/cart/list.jsp
  CultureCenter/src/main/webapp/resources/common/common.js
  CultureCenter/src/main/webapp/resources/common/images/icon-two-depth-select-check-black.svg
  CultureCenter/src/main/webapp/resources/common/js/application/integration/integrationList.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_branch.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_category.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/src/main/webapp/resources/common/js/common.js
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypage_cart.js
  CultureCenter/src/main/webapp/resources/common/js/script.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/AtlctMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MyPageCartMapper.xml
Labels: 🔨 Maintenance, ⚙ Setting, ✨ Feature

#86 마이페이지 관심지점 설정
  CultureCenter/src/main/java/com/culture/demo/controller/EtcController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/domain/MemberDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/inc/header.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/coupon/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/freebie/appList.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/freebie/detailList.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/teachereval/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/common.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/freebie/appList.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/freebie/detailList.js
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
Labels: ✨ Feature

#99 강좌 목록 + 강좌 상세 정보 페이지 구현
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassFormDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/SearchBranchDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TawardsDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TcareerDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TcertificateDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TeacherDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TeducationDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/guide/online/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/guide/settle/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/CartMapper.xml
Labels: ✨ Feature

#101 메인페이지 추천/카테고리/신규 강좌 출력 및 이미지 출력
  CultureCenter/src/main/java/com/culture/demo/controller/HomeController.java
  CultureCenter/src/main/java/com/culture/demo/domain/MainLectSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/resources/common/js/common.js
  CultureCenter/src/main/webapp/resources/common/js/main/mainCtrl.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/target/classes/log4j.xml
Labels: 🔨 Maintenance, ⚙ Setting, ✨ Feature

#103 Log4j.xml 수정
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/root-context.xml
  CultureCenter/src/main/webapp/WEB-INF/views/payment/step1.jsp
  CultureCenter/src/main/webapp/resources/common/js/payment/payment.js
Labels: ⚙ Setting, 📃 Docs

#105 메인페이지 공지사항 출력 기능 및 jsoup 추가
  CultureCenter/pom.xml
  CultureCenter/src/main/java/com/culture/demo/controller/HomeController.java
  CultureCenter/src/main/java/com/culture/demo/mapper/NoticeMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/NoticeService.java
  CultureCenter/src/main/java/com/culture/demo/service/NoticeServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/NoticeMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/getCategoryClassList.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/getNewClassList.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/getRecommendationClassList.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/home/index.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/atlct/view.jsp
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.xml
Labels: 🔨 Maintenance, ⚙ Setting, ✨ Feature

#108 지점 안내, 자주하는 문의 게시판 완성
  CultureCenter/bin/src/main/webapp/resources/common/js/information/faqCtrl.js
  CultureCenter/src/main/java/com/culture/demo/controller/BranchInfoController.java
  CultureCenter/src/main/java/com/culture/demo/controller/FaqInfoController.java
  CultureCenter/src/main/java/com/culture/demo/controller/TeacherApplicationController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AtlctDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/BranchDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FaqDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/TeacherDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/BranchInfoMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/FaqMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/TeacherMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/BranchInfoService.java
  CultureCenter/src/main/java/com/culture/demo/service/BranchInfoServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/FaqService.java
  CultureCenter/src/main/java/com/culture/demo/service/FaqServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/TeacherService.java
  CultureCenter/src/main/java/com/culture/demo/service/TeacherServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/BranchInfoMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/FaqMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/TeacherMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/WEB-INF/views/information/application/index.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/branch/list.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/information/branch/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/information/faq/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/information/faqCtrl.js
  CultureCenter/src/main/webapp/resources/common/js/information/teacherApp/cooperationRequest.js
  CultureCenter/src/main/webapp/resources/common/js/information/teacherApp/requestIndex.js
  CultureCenter/src/main/webapp/resources/common/js/information/teacherApp/teacherRequest.js
  CultureCenter/src/test/resources/log4j.xml
  CultureCenter/target/test-classes/log4j.xml
Labels: ✨ Feature

#107 수강후기 목록 페이지 ajax
  CultureCenter/src/main/java/com/culture/demo/controller/CommunityReviewController.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSearchDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/ReviewDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/ReviewMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/ReviewService.java
  CultureCenter/src/main/java/com/culture/demo/service/ReviewServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/ReviewMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/community/review/dtl.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/community/review/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/community/reviewController.js
  CultureCenter/src/main/webapp/resources/common/js/teacher/teacherCommon.js
  CultureCenter/target/classes/com/culture/demo/mapper/ReviewMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
Labels: ✨ Feature

#116 강좌 상태별 버튼 구현
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/OptionDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
Labels: ✨ Feature

#118 장바구니자동삭제 / 수강결제 페이지1 완료
  CultureCenter/src/main/java/com/culture/demo/controller/EtcController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MyPageCartController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/controller/PaymentController.java
  CultureCenter/src/main/java/com/culture/demo/domain/CartDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/ChildrenDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/FrmSubmitDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/CartMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/PaymentMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/CartService.java
  CultureCenter/src/main/java/com/culture/demo/service/CartServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/PaymentService.java
  CultureCenter/src/main/java/com/culture/demo/service/PaymentServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/CartMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/PaymentMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/root-context.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/cart/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/payment/step1.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/payment/step2.jsp
  CultureCenter/src/main/webapp/resources/common/js/member/addFamilyPop.js
  CultureCenter/src/main/webapp/resources/common/js/payment/payment.js
  CultureCenter/target/classes/com/culture/demo/mapper/CartMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
Labels: 🐞 Bug, 📃 Docs

#119 강사신청 step 1 -> 2 구현
  CultureCenter/pom.xml
  CultureCenter/src/main/java/com/culture/demo/controller/TeacherApplicationAjaxController.java
  CultureCenter/src/main/java/com/culture/demo/controller/TeacherApplicationController.java
  CultureCenter/src/main/java/com/culture/demo/domain/TeacherDTO.java
  CultureCenter/src/main/java/com/culture/demo/service/TeacherService.java
  CultureCenter/src/main/java/com/culture/demo/service/TeacherServiceImpl.java
  CultureCenter/src/main/webapp/resources/common/js/information/teacherApp/requestIndex.js
  CultureCenter/src/main/webapp/resources/common/js/information/teacherApp/teacherRequest.js
  CultureCenter/src/test/resources/log4j.xml
  CultureCenter/target/classes/com/culture/demo/mapper/BranchInfoMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/FaqMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/ReviewMapper.xml
  CultureCenter/target/classes/log4j.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.xml
  CultureCenter/target/test-classes/log4j.xml
Labels: ✨ Feature

#122 세부강좌 -> 수강결제step1 / 수강결제1 -> 수강결제2 인자 처리
  CultureCenter/src/main/java/com/culture/demo/controller/PaymentController.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AtlctMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/CartMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/PaymentMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/PaymentService.java
  CultureCenter/src/main/java/com/culture/demo/service/PaymentServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/CartMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/PaymentMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/payment/step2.jsp
  CultureCenter/src/main/webapp/resources/common/js/payment/payment.js
  CultureCenter/target/classes/com/culture/demo/mapper/CartMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.properties
Labels: 🐞 Bug, 📃 Docs

#126 수강신청 버튼, 장바구니 버튼 구현 완료
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/OptionDTO.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/resources/log4j.xml
  CultureCenter/src/main/webapp/META-INF/MANIFEST.MF
  CultureCenter/src/main/webapp/META-INF/maven/com.culture/demo/pom.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/log4j.xml
Labels: ✨ Feature

#130 시큐리티 및 비밀번호 암호화, 회원가입 환영 메일 발송 적용
  CultureCenter/bin/src/main/webapp/WEB-INF/spring/security-context.xml
  CultureCenter/pom.xml
  CultureCenter/src/main/java/com/culture/demo/controller/HomeController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MemberController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/domain/AuthVO.java
  CultureCenter/src/main/java/com/culture/demo/domain/MemberDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/security/CustomAccessDeniedHandler.java
  CultureCenter/src/main/java/com/culture/demo/security/CustomLoginSuccessHandler.java
  CultureCenter/src/main/java/com/culture/demo/security/CustomUserDetailsService.java
  CultureCenter/src/main/java/com/culture/demo/security/CustomerUser.java
  CultureCenter/src/main/java/com/culture/demo/service/EmailSenderService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/root-context.xml
  CultureCenter/src/main/webapp/WEB-INF/spring/security-context.xml
  CultureCenter/src/main/webapp/WEB-INF/views/home/index.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/inc/footer.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/inc/head.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/inc/header.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/login/index.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/login/result.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/join.jsp
  CultureCenter/src/main/webapp/WEB-INF/web.xml
  CultureCenter/src/main/webapp/resources/common/js/fnc.js
  CultureCenter/src/main/webapp/resources/common/js/member/member.js
  CultureCenter/src/main/webapp/resources/common/js/member/sso.js
Labels: ⚙ Setting, ✨ Feature

#133 강좌로 찾기, 수강신청 페이지 이동 구현
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/SearchBranchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/LecSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/src/main/webapp/META-INF/maven/com.culture/demo/pom.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/inc/layout.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_branch.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_category.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.xml
Labels: ✨ Feature

#135 차량번호 수정 Ajax
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/info.jsp
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypageMember.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/target/m2e-wtp/web-resources/META-INF/maven/com.culture/demo/pom.xml
Labels: ✨ Feature

#140 메인페이지 강좌 검색 + 파라미터 이슈 해결
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/controller/HomeController.java
  CultureCenter/src/main/java/com/culture/demo/domain/SearchBranchDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/META-INF/maven/com.culture/demo/pom.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/integration/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/integration/integrationList.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_branch.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/target/classes/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/CartMapper.xml
  CultureCenter/target/classes/com/culture/demo/mapper/MemberMapper.xml
Labels: ✨ Feature

#141 강좌 목록 - 팝업 열기 - 강좌로 찾기, 지점으로 찾기
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/mapper/LecSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/LecSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/LecSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchList_branch.js
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
  CultureCenter/target/classes/com/culture/demo/mapper/LecSearchMapper.xml
Labels: ✨ Feature

#142 강좌 상세 보기 - 리뷰 목록 및 ajax 출력 구현
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ClassFormDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/ReviewDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/ReviewServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/resources/common/images/icon-star-blank.svg
Labels: ✨ Feature

#146 대기접수 페이지 출력
  CultureCenter/src/main/java/com/culture/demo/controller/ApplicationSearchController.java
  CultureCenter/src/main/java/com/culture/demo/domain/ChildrenDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/MemberDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/AppSearchMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchService.java
  CultureCenter/src/main/java/com/culture/demo/service/AppSearchServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/AppSearchMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/application/search/view.jsp
  CultureCenter/src/main/webapp/resources/common/js/application/search/searchView.js
Labels: ✨ Feature

#127 마이페이지 > 대기자 조회 (시큐리티 제외)
  CultureCenter/src/main/java/com/culture/demo/controller/MypageInquiryController.java
  CultureCenter/src/main/java/com/culture/demo/controller/MypageWaitingController.java
  CultureCenter/src/main/java/com/culture/demo/domain/InquiryDTO.java
  CultureCenter/src/main/java/com/culture/demo/domain/WaitingListDTO.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MypageInquiryMapper.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MypageWaitingMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/InquiryService.java
  CultureCenter/src/main/java/com/culture/demo/service/InquiryServiceImpl.java
  CultureCenter/src/main/java/com/culture/demo/service/WaitingService.java
  CultureCenter/src/main/java/com/culture/demo/service/WaitingServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MypageInquiryMapper.xml
  CultureCenter/src/main/resources/com/culture/demo/mapper/MypageWaitingMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/inquiry/list.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/inquiry/list.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/inquiry/view.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/waiting/list.ajax
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/waiting/list.jsp
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypageInquiryCtrl.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypage_waiting.js
  CultureCenter/target/classes/com/culture/demo/mapper/MypageWaitingMapper.xml
Labels: ✨ Feature

#148 비밀번호 변경, 회원정보수정, 회원탈퇴(홈페이지 리다이렉트(아직)
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/mapper/MemberMapper.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/resources/com/culture/demo/mapper/MemberMapper.xml
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/info.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/up_member.jsp
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/up_pw.jsp
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypageMember.js
Labels: ✨ Feature

#153 동반 수강자 리스트,동반삭제, 비밀번호 변경, 회원정보 변경, 회원탈퇴
  CultureCenter/src/main/java/com/culture/demo/controller/MypageMemberController.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberService.java
  CultureCenter/src/main/java/com/culture/demo/service/MemberServiceImpl.java
  CultureCenter/src/main/webapp/WEB-INF/views/mypage/member/info.jsp
  CultureCenter/src/main/webapp/resources/common/js/member/addFamilyPop.js
  CultureCenter/src/main/webapp/resources/common/js/mypage/mypageMember.js
Labels: ✨ Feature
